<?php

class RemoveDuplicates
{

    /**
     * Changes the array in-place, removing duplicate entries.
     * @param int[] $nums the array to be changed.
     * @return int the number of unique elements in the array.
     */
    public static function execute(&$nums): int
    {
        if (count($nums) < 1) return 0;

        $k = 1; // The number of unique elements. I found that at least 1 should be unique xD
        $checkPos = 0; // The starting position to be checked.

        // Loops from the second position until the end.
        for ($i = 1; $i < count($nums); $i++) {
            if ($nums[$i] > $nums[$checkPos]) {
                $nums[$checkPos + 1] = $nums[$i];
                $checkPos++;
                $k++;
            }
        }

        return $k; // Return the number of unique elements.
    }

    /**
     * Test if the code above is valid. (Generated by AI but verified by me :>)
     * @return void
     */
    public static function runTests(): void
    {
        $tests = [
            [
                'input' => [1, 1, 2],
                'expectedCount' => 2,
                'expectedArray' => [1, 2]
            ],
            [
                'input' => [0, 0, 1, 1, 1, 2, 2, 3, 3, 4],
                'expectedCount' => 5,
                'expectedArray' => [0, 1, 2, 3, 4]
            ],
            [
                'input' => [1, 2, 3, 4, 5],
                'expectedCount' => 5,
                'expectedArray' => [1, 2, 3, 4, 5]
            ],
            [
                'input' => [],
                'expectedCount' => 0,
                'expectedArray' => []
            ],
            [
                'input' => [1, 1, 1, 1, 1],
                'expectedCount' => 1,
                'expectedArray' => [1]
            ],
        ];

        foreach ($tests as $index => $test) {
            $input = $test['input'];
            $expectedCount = $test['expectedCount'];
            $expectedArray = $test['expectedArray'];

            $actualCount = RemoveDuplicates::execute($input);

            // Asserting the number of unique elements.
            if ($actualCount !== $expectedCount) {
                echo "Test case {$index} failed: expected count {$expectedCount}, got {$actualCount}\n";
            } else {
                echo "Test case {$index} count passed\n";
            }

            // Asserting the modified array up to the number of unique elements.
            $actualArray = array_slice($input, 0, $actualCount);
            if ($actualArray !== $expectedArray) {
                echo "Test case {$index} failed: expected array " . implode(',', $expectedArray) . ", got " . implode(',', $actualArray) . "\n";
            } else {
                echo "Test case {$index} array passed\n";
            }
        }
    }
}

RemoveDuplicates::runTests();